# Generated by Django 2.2.5 on 2021-02-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexxi', '0002_auto_20210207_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
