# Generated by Django 2.2.5 on 2021-02-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexxi', '0004_auto_20210209_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
