# Generated by Django 2.2.5 on 2021-02-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexxi', '0005_post_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brief',
            field=models.TextField(),
        ),
    ]
